language: node_js
node_js:
  - "6"
os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install "$TRAVIS_NODE_VERSION"
  - npm install -g node-gyp

env:
  global:
    - CXX=g++-4.8
